#!/usr/bin/env python3
"""
Smart Second Brain - Vault Initialization Script
Initialize Obsidian vault with three-layer knowledge structure
"""

import os
import sys
import argparse
from pathlib import Path
import shutil

# Vault folder structure
VAULT_STRUCTURE = {
    # Raw Layer (00-Raw) - Original materials
    "00-Raw": {
        "抖音笔记": "抖音视频笔记",
        "公众号文章": "微信公众号文章",
        "微信读书": "微信读书笔记",
        "ima知识库": "IMA知识库导入",
        "临时收集": "临时收集的素材"
    },
    
    # Schema Layer (10-Schema) - Structured knowledge
    "10-Schema": {
        "对话知识": "WorkBuddy对话同步知识",
        "技术笔记": "技术相关笔记",
        "读书笔记": "结构化读书笔记",
        "ima知识库": "IMA知识库（已结构化）",
        "其他": "其他结构化知识"
    },
    
    # Wiki Layer (20-Wiki) - Refined output
    "20-Wiki": {
        "项目": "项目相关wiki",
        "概念": "概念解释和总结",
        "方法论": "方法论和实践指导",
        "输出成品": "可输出的成品内容"
    },
    
    # Other folders
    "30-Projects": "项目文件夹",
    "40-Archive": "归档文件夹",
    "50-Assets": {
        "图片": "图片资源",
        "视频": "视频资源",
        "音频": "音频资源"
    },
    "60-Diary": {
        "第二大脑系统日志": "系统执行日志",
        "周度总结": "周度总结",
        "知识质量验证报告": "质量验证报告",
        "知识精炼报告": "精炼报告"
    },
    "99-Templates": "笔记模板"
}

def create_folder_structure(vault_path):
    """Create vault folder structure"""
    print(f"📁 Creating vault structure at: {vault_path}")
    
    for folder, subfolders in VAULT_STRUCTURE.items():
        folder_path = Path(vault_path) / folder
        folder_path.mkdir(parents=True, exist_ok=True)
        print(f"  ✅ Created: {folder}")
        
        # Create subfolders
        if isinstance(subfolders, dict):
            for subfolder, description in subfolders.items():
                subfolder_path = folder_path / subfolder
                subfolder_path.mkdir(parents=True, exist_ok=True)
                print(f"    ✅ Created: {folder}/{subfolder} - {description}")
                
                # Create README for subfolder
                readme_path = subfolder_path / "README.md"
                if not readme_path.exists():
                    with open(readme_path, "w", encoding="utf-8") as f:
                        f.write(f"# {subfolder}\n\n{description}\n")
                        
        # Create .gitkeep to keep empty folders
        gitkeep_path = folder_path / ".gitkeep"
        if not gitkeep_path.exists():
            gitkeep_path.touch()

def copy_templates(vault_path, template_path):
    """Copy Obsidian templates to vault"""
    print(f"\n📝 Copying templates to vault...")
    
    template_dir = Path(template_path)
    vault_template_dir = Path(vault_path) / "99-Templates"
    
    if template_dir.exists():
        # Copy template files
        for template_file in template_dir.glob("*.md"):
            dest_file = vault_template_dir / template_file.name
            shutil.copy2(template_file, dest_file)
            print(f"  ✅ Copied: {template_file.name}")
    else:
        print(f"  ⚠️  Template directory not found: {template_path}")

def create_config_file(vault_path, config_path):
    """Create initial config file"""
    print(f"\n⚙️  Creating config file...")
    
    config_file = Path(config_path)
    if config_file.exists():
        print(f"  ⚠️  Config file already exists: {config_path}")
        return
    
    config_content = f"""# Smart Second Brain - Configuration
# Auto-generated by init_vault.py

vault_path: "{vault_path}"
template_path: "{vault_path}/99-Templates"

# Knowledge layers
layers:
  raw: "00-Raw"
  schema: "10-Schema"
  wiki: "20-Wiki"

# Automation
automation:
  enabled: true
  daily_sync: true
  dialog_sync: true
  quality_check: true
  weekly_refinement: true

# AI Configuration
ai:
  model: "mimo"
  temperature: 0.7
  max_tokens: 2000
"""
    
    with open(config_file, "w", encoding="utf-8") as f:
        f.write(config_content)
    
    print(f"  ✅ Created: {config_path}")

def create_readme(vault_path):
    """Create README for vault"""
    print(f"\n📚 Creating vault README...")
    
    readme_path = Path(vault_path) / "README.md"
    if readme_path.exists():
        print(f"  ⚠️  README already exists: {readme_path}")
        return
    
    readme_content = f"""# Smart Second Brain Vault

This is your AI-driven second brain vault.

## 📁 Folder Structure

### 00-Raw (Raw Layer)
Original materials - unprocessed content from various sources.

### 10-Schema (Schema Layer)
Structured knowledge - parsed and organized content.

### 20-Wiki (Wiki Layer)
Refined output - synthesized and actionable knowledge.

## 🤖 Automation Tasks

1. **Daily Knowledge Sync** - Auto-sync from multiple sources
2. **Obsidian Dialog Sync** - Sync WorkBuddy conversations
3. **Knowledge Quality Check** - Verify and validate knowledge
4. **Weekly Knowledge Refinement** - Summarize and refine weekly

## 📝 Usage

1. Put raw materials in `00-Raw/`
2. AI will automatically process and move to `10-Schema/`
3. Refined knowledge will be in `20-Wiki/`
4. Use templates in `99-Templates/`

## 🔗 Links

- Project: https://github.com/seeley1/smart-second-brain
- Documentation: [docs/](docs/)
- Issues: https://github.com/seeley1/smart-second-brain/issues

---

Created by [Smart Second Brain](https://github.com/seeley1/smart-second-brain)
"""
    
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
    
    print(f"  ✅ Created: {readme_path}")

def main():
    parser = argparse.ArgumentParser(description="Initialize Smart Second Brain Vault")
    parser.add_argument("--vault-path", required=True, help="Path to Obsidian vault")
    parser.add_argument("--template-path", default="../templates/obsidian", help="Path to template files")
    parser.add_argument("--config-path", default="config/config.yaml", help="Path to config file")
    
    args = parser.parse_args()
    
    print("🧠 Smart Second Brain - Vault Initialization")
    print("=" * 50)
    
    # Check if vault path exists
    vault_path = Path(args.vault_path)
    if not vault_path.exists():
        print(f"\n❌ Vault path does not exist: {vault_path}")
        print("Creating vault directory...")
        vault_path.mkdir(parents=True, exist_ok=True)
    
    # Create folder structure
    create_folder_structure(args.vault_path)
    
    # Copy templates
    copy_templates(args.vault_path, args.template_path)
    
    # Create config file
    create_config_file(args.vault_path, args.config_path)
    
    # Create README
    create_readme(args.vault_path)
    
    print("\n" + "=" * 50)
    print("✅ Vault initialization complete!")
    print(f"\n📂 Vault path: {vault_path.absolute()}")
    print(f"📝 Templates: {vault_path / '99-Templates'}")
    print(f"⚙️  Config: {args.config_path}")
    print("\n🚀 Next steps:")
    print("  1. Open Obsidian and set vault path")
    print("  2. Configure WorkBuddy automation tasks")
    print("  3. Start collecting knowledge!")
    print("\n💡 Need help? Check docs/ folder")

if __name__ == "__main__":
    main()
